### ISSUE TITLE
Support more exception types

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#299]
For example, if an `IllegalArgumetException` is thrown from JS that’s the exception that should be thrown in JVM.

**Comment by swankjesse** [comment]
Here’s my sense for built-in exception types:

 * Throwable
   * Error
     * AssertionError
   * Exception
     * RuntimeException
       * NullPointerException
       * IllegalStateException
       * IllegalArgumentException
       * UnsupportedOperationException

**Comment by veyndan** [comment]
What happens when we get a JVM-only exception (say, `FileNotFoundException`) and we want to throw it in JS? 
 * Throw ZiplineException
 * Throw Exception
 * Throw common superclass (`IOException` ?)

Maybe we always throw `ZiplineException` for all failures? And discourage using exceptions for control flow across the Zipline boundary.

**Comment by swankjesse** [comment]
We want to have different exceptions for two use cases:

 * Application code threw an exception
 * Application code used zipline wrong

**Comment by swankjesse** [comment]
Current decision is to not make exception types transparent. It’s too difficult to do well generally.
