### ISSUE TITLE
Zipline Loader Plan

### ISSUE THREAD

**Issue by adrw** [cashapp/zipline#381]
This returns once all of the modules in [manifest] have been loaded into [zipline].
This function can be canceled, but doing so leaves [zipline] in an undefined state.

version zero:
download each file sequentially
call Zipline.loadJsModule()

version one:
download each file sequentially if not stored on disk
store files on disk using okio.FileSystem
gotcha: atomicMove()
gotcha: download fails, this will leave garbage around forever
call Zipline.loadJsModule()

version two:
same as version one, but it doesn't leave garbage around forever
probably Sqlite to store downloads in flight
call Zipline.loadJsModule()

version three:
download in parallel
load as soon as downloads finish
honor topo sort
https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/cache/DiskLruCache.kt

version four:
prune old files
note that a file that has been pruned might also be loaded shortly after pruning; perhaps
even between deleting on disk and deleting in DB

**Comment by swankjesse** [comment]
More stuff for my wishlist:

 * [x] Rather than using a Mutex to limit access to the Zipline, use `withContext()` with a user-provided `CoroutineDispatcher`. That’s just as good and plays better with our concurrency model. (Every Zipline instance is thread-confined to a single-threaded Dispatcher; this keeps the concurrency fast and easy.)
  * [x] Integration test with a stubbed out HTTP client that just marks some global state about what was loaded. Maybe append to a global string named `globalThis.log` with what was loaded?
  * [x] Change the project from Kotlin/JVM to Kotlin/Multiplatform. The biggest gotcha here is renaming `src/main/kotlin` to `src/commonMain/kotlin` !
  * [x] Move `ZiplineFile` from the core `zipline` module to the `zipline-loader` module. 
  * [x] Rename `ZiplineModule.files` to `ZiplineModule.modules` and make that a `Map<String, ZiplineModule>`.
  * [x] Enable kotlinx.serialization JSON encoding for ZiplineManifests. Test this; we’re going to soon have a lot of files in this format!
  * [x] Get the Gradle plugin to emit a `ZiplineManifest` file. (What should the extension be? We have `.zipline` for each module, though we can change that.)
  * [x] Square open source copyright headers on every `.kt` file.

**Comment by adrw** [comment]
Moar
- [ ] change existing tests to use define()
- [x] the manifest test should not include all this code,
  just manually write a smaller thing
- [x] the body of the js function in the manifest test should throw an error so we know it's not ever run, only compiled to bytecode / manifest
- [x] split out the Gradle machinery from the business logic of the task, add unit test for specifically new dependencies.js
- [x] .ziplinem -> .zipline.json
- [x] write ZiplineLoader.loadManifest()

**Comment by adrw** [comment]
- [ ] upload manifests
- [ ] update mpp use of Zipline Loader
- [x] cache check of local file hashes before downloading

**Comment by swankjesse** [comment]
CDN structure for Treelot:
https://github.com/squareup/cash-treelot/issues/33

Structure for embedding artifacts in prebuilt app store releases:

```
cash-android.apk (this is like a .jar file)
  classes.dex
  treehouse/
    releases/
      prebuilt.zipline.json
    kotlin-kotlin-stdlib-js-ir/
      03bbc09a76454e4be9ba6baa3e181d2face1f44f150abfd0e928f4e7537e2b98.zipline
    payment-history-paymentHistoryKt.js/
      f6bf076fa5d9da4a797b5662615d46be188637050843bae95171e8bd87c26bfe.zipline
```

`prebuilt.zipline.json` is the built-in manifest.
The other files are built-in .zipline files referenced by that manifest.

**Comment by swankjesse** [comment]
@adrw I think this is done!
