### ISSUE TITLE
Future-proof experiment: alternate bytecodes

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#624]
Worth confirming we could run an alternate bytecode format in Zipline in a forwards-compatible way.

Manifests currently contain entries like this:
```
    "./kotlin-kotlinx-atomicfu-runtime-js-ir.js": {
      "url": "kotlin-kotlinx-atomicfu-runtime-js-ir.zipline",
      "sha256": "b56f9b874d947377ec32af145e41e7d78d0e2f8285719f3d85f3db2c3ed744ed"
    },
```

A potential future version’s manifest would have two links:
```
    "./kotlin-kotlinx-atomicfu-runtime-js-ir.js": {
      "url": "kotlin-kotlinx-atomicfu-runtime-js-ir.zipline",
      "sha256": "b56f9b874d947377ec32af145e41e7d78d0e2f8285719f3d85f3db2c3ed744ed"
      "wasmUrl": "kotlin-kotlinx-atomicfu-runtime-js-ir.zipline.wasm",
      "wasmSha256": "e316d2e93beb008fe2d7635621041bede8b910f7a7383b925c026b465b77f4db",
    },
```

No urgency to build this but we should confirm that current manifest loading can handle this. (Signing might interfere?)

**Comment by JakeWharton** [comment]
WASM is a different compilation target of the Kotlin compiler, not a transpilation target for compiled JS (although perhaps there exists a compiler which could do that). I don't think it's clear whether we can achieve things such as splitting on library boundaries with WASM. I suspect WASM to be sufficiently different enough that it's an entirely different manifest major version rather than one that coexists with the existing manifest+loader.

**Comment by swankjesse** [comment]
I‘m closing this in favor of another issue with a similar implementation but in service of a different goal.
https://github.com/cashapp/zipline/issues/717
