### ISSUE TITLE
QuickJS fork?

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/zipline#747]
QuickJS seems like abandonware. Given our intent to switch to a WASM runtime long-term and Kotlin/JS being stuck emitting ES5 JS it's actually not a huge deal. We're fine for a few years, although hopefully we won't take that long to switch.

However, the community has a bunch of PRs and patches to QuickJS that might be useful. We should consider maintaining those as patch files which we apply to the QuickJS sources that we already ingest. At worst there's new QuickJS releases and we have to reconcile the patches each time (assuming they're not integrated upstream). At best we get some meaningful improvements to things like performance or line numbers or support for Windows.

**Comment by JakeWharton** [comment]
It's not _really_ a fork since my proposal is to apply patches to the source inside our repo. Something we've historically done for every JS engine in order to hook up the timezone to Android's APIs.

It's more taking this approach farther since the likelihood of future QuickJS releases is low.

**Comment by swankjesse** [comment]
I’m on board generally, but there’s a catch...

We’re using QuickJS bytecode as if it had a stable encoding, but the encoded form relies on generated IDs that can change with updates to the runtime.

I’ve taken a shortcut by not building a versioned & stable bytecode, and the cost of this is that certain kinds of upgrades are difficult. In particular, anything that defines new values in `quickjs-opcode.h` isn’t likely compatible with existing bytecode files. There’s other symbols that are fragile to update.

My planned mitigation for this is to build N artifacts for N QuickJS versions, which will get ugly fast. We could also transcode using the [zipline-bytecode encoder](https://github.com/cashapp/zipline/tree/trunk/zipline-bytecode), though that’s also an operational pain.

Patches that don’t impact encoding of bytecode? Let’s apply ’em.
Otherwise I’m happy to [wait for WASM](https://github.com/cashapp/zipline/issues/717).

**Comment by swankjesse** [comment]
No action to take on this.
